### ISSUE TITLE
로고 이미지 버그 수정

### ISSUE THREAD

**Issue by NohSiHeon** [JHLee0891/ToHard-Make-Team-Name#12]
- 홈 로고 아이콘 클릭시 정렬 드롭다운 메뉴 보이는 이슈 발생

**Comment by JHLee0891** [comment]
와 이슈!

**Comment by JHLee0891** [comment]
![image](https://github.com/JHLee0891/ToHard-Make-Team-Name/assets/68465436/7e28046d-d3f1-48e6-b017-3e60c4b98816)
홈버튼에 붙어있던 spen 드롭다운 기능 삭제하여 버그 수정
